name: Windows VM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download ngrok
        run: choco install ngrok -y

      - name: Set ngrok token
        run: ngrok config add-authtoken TU_TOKEN

      - name: Configure RDP
        shell: powershell
        run: |
          net user runneradmin MyWin2026!
          net localgroup administrators runneradmin /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start ngrok
        shell: powershell
        run: |
          Start-Process ngrok -ArgumentList "tcp 3389"
          Start-Sleep -Seconds 20
          Invoke-RestMethod http://127.0.0.1:4040/api/tunnels

      - name: Keep alive
        shell: powershell
        run: |
          while ($true) {
            Start-Sleep -Seconds 60
          }
